#!/bin/sh
#
# Kernel hook for assembling ucode
#
# Arguments passed to this script: $1 pkgname, $2 version.
#
PKGNAME="$1"
VERSION="$2"

. "$ROOTDIR/etc/default/ucode-image-gen"

if [ "$UCODE_UNIVERSAL" = "1" ]; then
        args=-universal
fi

ucode-image-gen -output "/boot/ucode.img" "$args"
