#!/bin/sh
#
# Kernel hook for removing a uki
#
# Arguments passed to this script: $1 pkgname, $2 version.
#
PKGNAME="$1"
VERSION="$2"

rm -rf "/efi/EFI/Linux/$VERSION.efi"
printf "Finished removing unified kernel image\n"
