#!/bin/sh
#
# Kernel hook for gummiboot.
# Heavily based on 50-gummiboot
#
# Arguments passed to this script: $1 pkgname, $2 version.
#
PKGNAME="$1"
VERSION="$2"

checksum() {
    b2sum "$1" | cut -d " " -f 1 
}

esp="$ROOTDIR/efi"
entry_dir="$ROOTDIR/etc/limine"
name="void-$VERSION"
config="$esp/limine.cfg"
bootloader="$ROOTDIR/efi/EFI/BOOT/BOOTX64.EFI"

[ -d "$esp" ] || exit 0

[ -e "$config" ] && sed -i "/$name/,+3d" "$config"

limine enroll-config "$bootloader" $(checksum "$config")
sbctl sign -s "$bootloader"

cd "$entry_dir" || exit 0
rm -rf "$VERSION"
