#!/bin/sh
#
# Kernel hook for limine and unified kernel images.
#
# Arguments passed to this script: $1 pkgname, $2 version.
#
PKGNAME="$1"
VERSION="$2"

checksum() {
    b2sum "$1" | cut -d " " -f 1 
}

esp="$ROOTDIR/efi"
entry_dir="$ROOTDIR/etc/limine"
name="void-$VERSION"
config="$esp/limine.cfg"
bootloader="$ROOTDIR/efi/EFI/BOOT/BOOTX64.EFI"

[ -d "$esp" ] || exit 0

[ -d "$entry_dir" ] || mkdir "$entry_dir"

cat <<-EOF > "$entry_dir/$VERSION"

:$name
    PROTOCOL=chainload
    IMAGE_PATH=boot:///EFI/Linux/$VERSION.efi#$(checksum "$esp/EFI/Linux/$VERSION.efi")
EOF

cat "$ROOTDIR/etc/default/limine" "$entry_dir/$VERSION" > "$config"

find "$entry_dir" -maxdepth 1 -type f |
    grep -v "$VERSION" | while read -r entry; do
        cat "$entry" >> "$config"
    done

limine enroll-config "$bootloader" $(checksum "$config")
sbctl sign -s "$bootloader"
